apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  namespace: nginx-app
spec:
  selector:
    app: nginx
  ports:
    - port: 8080
      targetPort: 80
  externalTrafficPolicy: Local
  loadBalancerIP: 0.0.0.0
  type: LoadBalancer