apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  namespace: nginx-app
  # annotations:
  #   kube-vip.io/loadbalancerIPs: '192.168.135.212'
spec:
  selector:
    app: nginx
  ports:
    - port: 8080
      targetPort: 80
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  # LoadBalancerIP: '192.168.135.212'
