apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  namespace: nginx-app
  annotations:
    kube-vip.io/loadbalancerIPs: '192.168.138.188'
  labels:
    implementation: kube-vip
    ipam-address: '192.168.138.188'
spec:
  selector:
    app: nginx
  ports:
    - port: 8080
      targetPort: 80
  externalTrafficPolicy: Local
  type: LoadBalancer
